name: "Run Tests"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

concurrency:
  group: testing-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Determine if tests should be run based on commit message.
  check_skip:
    name: Determine if CI should be skipped
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.result_step.outputs.ci-skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: result_step
        uses: mstachniuk/ci-skip@master
        with:
          commit-filter: "[skip ci];[ci skip];[skip github]"
          commit-filter-separator: ";"

  run_unit_tests:
    name: Unit tests
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: "Set up python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Gradec"
        shell: bash {0}
        run: pip install -e .[tests]
      - name: "Run tests"
        if: matrix.os == 'ubuntu-latest'
        uses: GabrielBB/xvfb-action@v1.5
        with:
          options: -screen 0 1600x1200x24
          run: make unittest
      - name: "Run tests"
        if: matrix.os == 'macos-latest'
        shell: bash {0}
        run: make unittest
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unit_${{ matrix.os }}_${{ matrix.python-version }}
          path: coverage.xml
        if: success()

  run_unit_tests_with_minimum_dependencies:
    name: Unit tests with minimum dependency versions
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: "Set up python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Install Gradec"
        shell: bash {0}
        run: pip install -e .[minimum,tests]
      - name: "Run tests"
        if: matrix.os == 'ubuntu-latest'
        uses: GabrielBB/xvfb-action@v1.5
        with:
          options: -screen 0 1600x1200x24
          run: make unittest
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unit_minimum
          path: coverage.xml
        if: success()

  upload_to_codecov:
    name: Upload coverage
    needs: [run_unit_tests, run_unit_tests_with_minimum_dependencies]
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
